name: CI

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum

      - name: Линтер
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6
          golangci-lint run --config ../.golangci.yaml ./...

      - name: Тесты
        run: go test ./... -race
